version: '3'
services:
  chatbotserver:
    container_name: chatbot
    restart: always
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traffic"
      - "traefik.frontend.rule=Host:${CHATBOT_DOMAIN}.${BASE_URL}"
      - "traefik.port=80"
    networks:
      - traffic
networks:
  traffic:
    external: true
